### ISSUE TITLE
Cannot open the serial port. Device is not open

### ISSUE THREAD

**Issue by shady236** [wh201906/SerialTest#19]
Hey, I'm trying to use the program under Ubuntu 18.04. PL2303 USB to TTL converter is connected on ttyUSB0 port. However the program doesn't recognize its vendor or product IDs as shown.
![Screenshot from 2023-01-09 19-38-10](https://user-images.githubusercontent.com/71782873/211372927-e99d346a-027f-4989-8cfd-1151ea504fdc.png)

when I try to open this port, it shows a message "Cannot open the serial port. Device is not open". 
![Screenshot from 2023-01-09 19-38-14](https://user-images.githubusercontent.com/71782873/211373424-1259a2b1-353f-4184-aa3a-733d58a6d7b0.png)

In terminal, vendor or product IDs are recognized as shown. How can I fix this?
![Screenshot from 2023-01-09 19-40-32](https://user-images.githubusercontent.com/71782873/211372943-abde35bb-eb2d-4fc5-a161-364d46b5700a.png)

**Comment by wh201906** [comment]
Thanks for your feedback. I will check it these days.

**Comment by shady236** [comment]
I've added it to dialout, but the same issue exists.

**Comment by wh201906** [comment]
Could you please run `ls -l /dev` to check the permissions of the `/dev/ttyUSB0`? You can post your result there.
Plus, do other serial port tools work for `/dev/ttyUSB0`?

**Comment by shady236** [comment]
Here is the result of `ls -l /dev/ttyUSB0`
![Screenshot from 2023-02-06 23-52-50](https://user-images.githubusercontent.com/71782873/217096596-5c46bc13-73ca-463d-b909-2401f4d23f53.png)

No, I haven't tried other serial port tools

**Comment by wh201906** [comment]
How about setting permission of `ttyUSB0` to `666`(r+w for all users) then run `SerialTest` in the same shell? I'm still doubting it's a permission issue.

**Comment by shady236** [comment]
Still not working, I've tried another serial port tool (CuteCom) and it's working. I think there's no problem in permissions.

**Comment by wh201906** [comment]
How did you install SerialTest?

**Comment by wh201906** [comment]
> I think there's no problem in permissions.

How about running `sudo ./SerialTest`? You can try this if you wish.

**Comment by shady236** [comment]
I've installed SerialTest from flatHub 
https://flathub.org/apps/details/io.github.wh201906.serialtest
using the command 
`flatpak install flathub io.github.wh201906.serialtest`

**Comment by shady236** [comment]
This is what I got when running it through terminal. I hope it's useful
![Screenshot from 2023-02-07 15-21-31](https://user-images.githubusercontent.com/71782873/217256331-ee5f23f6-7dab-4fc9-8de1-097645b9b289.png)
is is what I got when running it through terminal

**Comment by wh201906** [comment]
I build SerialTest directly then I don't get the problems, so I guess there might be something wrong in the flatpak packaging of this app.
You can try to build it from the source code if you wish. I will check the flatpak packaging when I'm free.

**Comment by wh201906** [comment]
@shady236 I have updated the metadata of the flatpak.
Since I'm not familiar with it, I don't know if the change takes effect immediately. Would you like to try it?

**Comment by wh201906** [comment]
@shady236 Hi. Please follow the instructions from [Flathub](https://flathub.org/apps/details/io.github.wh201906.serialtest) to install SerialTest. I've tested it on Ubuntu 18.04(Live CD) and it works.(You need to add the current user to `dialout`, of course.)
