### ISSUE TITLE
界面 Bug：悬浮窗口被关闭且难以恢复

### ISSUE THREAD

**Issue by 14725** [wh201906/SerialTest#22]
Bug 源于误操作，在 Windows 10 下发生。

复现方法：
1. 打开本“串口调试助手”
2. 点击右上角的按钮（如图所示  ![微信截图_20230207221124](https://user-images.githubusercontent.com/32530438/217268408-5caeddbe-e70f-44d8-a71a-aad03a960d3f.png) ）
3. 对新开的窗口按下 `Alt + F4`
4. 然后复现成功：我该怎么再打开这个窗口/选项卡呢？

**Comment by wh201906** [comment]
确实有bug。悬浮窗口的关闭事件应该被拦截下来
我尽量在下一个版本修复

**Comment by wh201906** [comment]
另外，悬浮窗口可以通过双击顶部或者拖动的方式回到主窗口。

**Comment by 14725** [comment]
谢谢！（等待修复）
