### ISSUE TITLE
安卓编译

### ISSUE THREAD

**Issue by zj2023410** [wh201906/SerialTest#25]
你好大佬。编译安卓，需要哪个版本的qt版本来支持

**Comment by wh201906** [comment]
5.15的任意版本应该都可以

**Comment by Q356646** [comment]
![截图_20230410130631](https://user-images.githubusercontent.com/106804231/230830155-dc303495-807e-4e35-856a-ea8b2b783d10.png)
你好！我的qt版本是5.15.2使用最新的0.2.2版本编译。出现图示的问题。这个是绘图那个需要安装什么包吗？由于没有怎么使用过曲线绘图，这个编译错误应该怎么处理

**Comment by Q356646** [comment]
![截图_20230410130909](https://user-images.githubusercontent.com/106804231/230830430-cb3b9024-14ce-4798-8c35-efa676e9c960.png)

**Comment by Q356646** [comment]
你好！我的qt版本是5.15.2使用最新的0.2.2版本编译。出现图示的问题。这个是绘图那个需要安装什么包吗？由于没有怎么使用过曲线绘图，这个编译错误应该怎么处理
![截图_20230410131007](https://user-images.githubusercontent.com/106804231/230830556-c18c73f3-23f8-46da-a73b-a2198d9f3e6f.png)
![截图_20230410131027](https://user-images.githubusercontent.com/106804231/230830585-e4ee0775-6317-4b54-9ddd-fd079bbe84d8.png)

**Comment by wh201906** [comment]
你可以参考一下这里的编译步骤
https://github.com/wh201906/SerialTest/blob/master/doc/README/README_zh_CN.md#3-%E9%80%89%E6%8B%A9%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8qcustomplot
你需要去QCustomPlot的官网上下载.cpp和.h文件，然后放到src文件夹下面，再编译

**Comment by zj2023410** [comment]
好的！谢谢解答
