### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [wh201906/SerialTest#27]
https://hosted.weblate.org/projects/serialtest/app/#information says "proprietary",
but it should say `LGPLv3-or-later` like https://github.com/wh201906/SerialTest/blob/master/LICENSE

It can be changed in
https://hosted.weblate.org/settings/serialtest/app/
and
https://hosted.weblate.org/settings/serialtest/glossary/

:)

**Comment by wh201906** [comment]
Thank you for point this out!
I'm not ready to use Weblate with this project now. Plus, I'm preparing changing the license of this project.
https://github.com/wh201906/SerialTest/discussions/26
When everything is ready, I will update the Weblate page to keep things fresh.

**Comment by wh201906** [comment]
Fixed. Thanks!

**Comment by wh201906** [comment]
@comradekingu Sorry. I accidentally deleted the translation of `nb_NO` when configuring Weblate. Would you like to start it again?

**Comment by comradekingu** [comment]
@wh201906 
Will do when I get around to it. All the components are added for "nb_NO".
