### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [wh201906/SerialTest#32]
Please support the Android 13 "Themed App Icons" feature.
#AdaptiveIcon

    

![Screenshot_2023-06-12-04-30-39-146_de.mm20.launcher2.release.jpg](https://github.com/wh201906/SerialTest/assets/23485114/b6c4f107-ca33-4530-8c1f-0efe9ae1fcf7)

**Comment by wh201906** [comment]
I found that some of the apps you listed doesn't have a specific configuration for the monochrome icon, and I don't know why the OS cannot change the icon into a monochrome one while others can. It will be much helpful if you could provide some information about it.

**Comment by sebastien46** [comment]
> It will be much helpful if you could provide some information about it.

Here is the [official Android developer documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) on the subject

**Comment by wh201906** [comment]
@sebastien46 Thanks. It's useful.

**Comment by sebastien46** [comment]
@wh201906 here's a mockup I made using inkscape:
![ic_launcher_monochrome](https://github.com/wh201906/SerialTest/assets/57289288/51a09ed9-f1ed-4cb4-ae31-cbcc406a0179)

I also saw that you didn't use the vector file for drawing the regular / adaptive app icon, so here's a version of that:

![ic_launcher_foreground](https://github.com/wh201906/SerialTest/assets/57289288/a5eb9005-313a-441a-bfb1-70561f64ae70)

I would've tried making a PR but the QT Creator VCS tree is really too confusing for me 😄

**Comment by wh201906** [comment]
@sebastien46 Thank you so much! I'll try the information you provided.

**Comment by wh201906** [comment]
I finally got an Android 14 device to test it. This is implemented in commit 1e62c938d718d4f0be21d3e04ad45cff3d962afa and it's working on my device.

**Comment by wh201906** [comment]
> When it'll implemented in new update

Ah sorry I didn't get the notification of this reply.
I'll release it in around 1~2 weeks.

**Comment by saltsoftdrink** [comment]
> > When it'll implemented in new update
> 
> Ah sorry I didn't get the notification of this reply. I'll release it in around 1~2 weeks.

Thanks Man!

**Comment by wh201906** [comment]
@saltsoftdrink The new release is out, but it takes some time for F-Droid to build it.

**Comment by saltsoftdrink** [comment]
> @saltsoftdrink The new release is out, but it takes some time for F-Droid to build it.

Upload in release section of github

**Comment by wh201906** [comment]
The apks of older releases are also from F-Droid. I have to wait the build process of F-Droid otherwise the apk signature will change.

**Comment by wh201906** [comment]
The apk can be downloaded on [F-Droid](https://f-droid.org/packages/priv.wh201906.serialtest/) or [GitHub Releases](https://github.com/wh201906/SerialTest/releases/tag/V0.3.4)
