### ISSUE TITLE
可以增加Linux版本的Release包吗？

### ISSUE THREAD

**Issue by HartleyLau** [wh201906/SerialTest#33]
Linux下缺少好用的串口/网络调试工具，希望能够提供一个Linux版本的二进制包

**Comment by wh201906** [comment]
你可以试一下通过FlatHub安装，支持绝大部分的桌面发行版
https://flathub.org/apps/io.github.wh201906.serialtest
如果你用的是Arch Linux系统，还可以通过yay安装AUR上的版本
https://aur.archlinux.org/packages/serialtest
