### ISSUE TITLE
可以自定义数据协议吗？

### ISSUE THREAD

**Issue by LandyZou** [wh201906/SerialTest#35]

**Comment by wh201906** [comment]
不太明白，可以详细描述一下吗

**Comment by LandyZou** [comment]
感谢回复！我想问的是在波形绘制的时候，可以自定义协议解析数据吗？例如一个8字节的数据，数据位只占其中的两个字节，用的是串口协议


----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Self&nbsp;Not&nbsp;Found ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 下午4:40
收件人："wh201906/SerialTest" ***@***.***&gt;;
抄送："邹浪 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [wh201906/SerialTest] 可以自定义数据协议吗？ (Issue #35)
-----------------------------------

 

 
不太明白，可以详细描述一下吗

**Comment by wh201906** [comment]
目前还不支持此功能
一个变通的办法是用python进行转发，把串口数据转发到tcp上，在此过程中根据你需要的格式进行转化
方便告知一下你所使用的具体协议格式吗？

**Comment by LandyZou** [comment]
一帧数据包括 帧头（4）+有效数据（2） +校验和（1）+附加校验（1）&nbsp; &nbsp;长度8字节
 
例：
 
AA FF F1 02 08 00 4F
 
详细说明：
 
[0-2]AA FF F1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 固定帧头
 
[3]02&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 有效数据长度0x02（2），STM32 ADC一个通道为u16型数据
 
[4-5]08 00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ADC采样值，uint16型数据，小端在前 0x0080=128
 
[6]A4 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校验和&nbsp; &nbsp;&nbsp;前面6字节累加和，取低八位
 
[7]48 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 附加校验&nbsp; 前面7字节累加和，取低八位

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Self&nbsp;Not&nbsp;Found ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 下午4:47
收件人："wh201906/SerialTest" ***@***.***&gt;;
抄送："邹浪 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [wh201906/SerialTest] 可以自定义数据协议吗？ (Issue #35)
-----------------------------------

 

 
目前还不支持此功能
 一个变通的办法是用python进行转发，把串口数据转发到tcp上，在此过程中根据你需要的格式进行转化
 方便告知一下你所使用的具体协议格式吗？

**Comment by wh201906** [comment]
前6个字节看懂了，但是第7和第8个你给出的是00 4F，但是解释部分却是A4 48。这一块是写错了吗？
还有一个问题，如果08 00对应0x0080，那么除了大小端以外可能还存在按位逆序或者移位的操作。最好是能多给几组数据包和对应数值的关系方便分析。
另外，用邮件回复格式会乱，方便在github上直接回
复吗？

**Comment by LandyZou** [comment]
好的，十分感谢回复，我到github再给出详细的回复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Self&nbsp;Not&nbsp;Found ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 下午5:01
收件人："wh201906/SerialTest" ***@***.***&gt;;
抄送："邹浪 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [wh201906/SerialTest] 可以自定义数据协议吗？ (Issue #35)
-----------------------------------

 

 
前6个字节看懂了，但是第7和第8个你给出的是00 4F，但是解释部分却是A4 48。这一块是写错了吗？
 还有一个问题，如果08 00对应0x0080，那么除了大小端以外可能还存在按位逆序或者移位的操作。最好是能多给几组数据包和对应数值的关系方便分析。
 另外，用邮件回复格式会乱，方便在github上直接回
 复吗？

**Comment by LandyZou** [comment]
一帧数据包括 帧头（4）+有效数据（2） +校验和（1）+附加校验（1）   长度8字节
例：AA FF F1 02 08 00 A4 48
详细说明：
[0-2] AA FF F1			固定帧头
[3] 02				有效数据长度0x02（2），STM32 ADC一个通道为u16型数据
[4-5] 08 00			ADC采样值，uint16型数据，小端在前 0x0080=128
[6] A4 				校验和    前面6字节累加和，取低八位，即：AA + FF +F1 + 02 + 08 + 00 = 2A4（十六进制加法），取低8位为：A4
[7] 48 				附加校验  前面7字节累加和，取低八位

**Comment by wh201906** [comment]
> [4-5] 08 00 ADC采样值，uint16型数据，小端在前 0x0080=128

这里你确定是0x0080=128而不是0x0008=8吗？后者是标准的小端序，你给出的应该是半字节交换
格式敲定下来之后我可以写个简单的python脚本帮你把收到的串口数据转发到SerialTest上绘图

**Comment by LandyZou** [comment]
确定是这样，有个调转


----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Self&nbsp;Not&nbsp;Found ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 下午5:15
收件人："wh201906/SerialTest" ***@***.***&gt;;
抄送："邹浪 ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [wh201906/SerialTest] 可以自定义数据协议吗？ (Issue #35)
-----------------------------------

 

  
[4-5] 08 00 ADC采样值，uint16型数据，小端在前 0x0080=128
  
这里你确定是0x0080=128而不是0x0008=8吗？后者是标准的小端序，你给出的应该是半字节交换
 格式敲定下来之后我可以写个简单的python脚本帮你把收到的串口数据转发到SerialTest上绘图

**Comment by wh201906** [comment]
那如果收到的数据帧第4, 5字节分别是 12 34，对应的采样值是0x4321吗？

**Comment by LandyZou** [comment]
是的，十分感谢！









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 Self Not ***@***.***&gt; 于2023年6月19日(周一) 下午5:24写道:

  

 
那如果收到的数据帧第4, 5字节分别是 12 34，对应的采样值是0x4321吗？

**Comment by wh201906** [comment]
大概是这么个样子，因为没设备测试所以你要自己试一下
```
import serial
import socket

# 串口配置
SERIAL_PORT = "COM3"  # 替换为你的串口号
BAUD_RATE = 9600  # 波特率，根据实际情况修改

# TCP服务器配置
SERVER_IP = "0.0.0.0"  # 监听所有可用的网络接口
SERVER_PORT = 12345  # 替换为服务器的端口号

# 数据包格式
PACKET_HEAD = b"\xAA\xFF\xF1"
PACKET_LEN = 8


# 处理数据
def process_data(data):
    ptr = 0
    handled = 0
    values = []
    while True:
        ptr = data.find(PACKET_HEAD, handled)
        if ptr == -1:
            break
        if len(data) - ptr < PACKET_LEN:
            break
        value = data[ptr + 4] + (data[ptr + 5] << 8)
        values.append(value)
        handled = ptr + PACKET_LEN
    return values, handled


# 创建串口对象
ser = serial.Serial(SERIAL_PORT, BAUD_RATE)

# 创建TCP服务器套接字
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
    # 绑定服务器地址和端口
    server_socket.bind((SERVER_IP, SERVER_PORT))
    print("服务器已启动，正在监听端口", SERVER_PORT)

    # 开始监听连接
    server_socket.listen(1)

    # 等待客户端连接
    client_socket, client_address = server_socket.accept()
    print("已连接到客户端", client_address)

    values = []
    data = bytearray()
    while True:
        # 从串口读取数据
        new_data = ser.read_all()
        if new_data is not None:
            data += new_data
        new_values, handled = process_data(data)
        for value in new_values:
            client_socket.send(str(value).encode() + "\n")
        data = data[handled:]

except serial.SerialException as e:
    print("串口连接错误:", e)
except socket.error as e:
    print("网络连接错误:", e)
finally:
    # 关闭串口和套接字
    ser.close()
    server_socket.close()

```

**Comment by LandyZou** [comment]
好的，非常感谢！我测试一下









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 Self Not ***@***.***&gt; 于2023年6月19日(周一) 晚上6:47写道:

  


大概是这么个样子，因为没设备测试所以你要自己试一下
import serial import socket # 串口配置 SERIAL_PORT = "COM3"  # 替换为你的串口号 BAUD_RATE = 9600  # 波特率，根据实际情况修改 # TCP服务器配置 SERVER_IP = "0.0.0.0"  # 监听所有可用的网络接口 SERVER_PORT = 12345  # 替换为服务器的端口号 # 数据包格式 PACKET_HEAD = b"\xAA\xFF\xF1" PACKET_LEN = 8 # 处理数据 def process_data(data):     ptr = 0     handled = 0     values = []     while True:         ptr = data.find(PACKET_HEAD, handled)         if ptr == -1:             break         if len(data) - ptr < PACKET_LEN:             break         value = data[ptr + 4] + (data[ptr + 5] << 8)         values.append(value)         handled = ptr + PACKET_LEN     return values, handled # 创建串口对象 ser = serial.Serial(SERIAL_PORT, BAUD_RATE) # 创建TCP服务器套接字 server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) try:     # 绑定服务器地址和端口     server_socket.bind((SERVER_IP, SERVER_PORT))     print("服务器已启动，正在监听端口", SERVER_PORT)     # 开始监听连接     server_socket.listen(1)     # 等待客户端连接     client_socket, client_address = server_socket.accept()     print("已连接到客户端", client_address)     values = []     data = bytearray()     while True:         # 从串口读取数据         new_data = ser.read_all()         if new_data is not None:             data += new_data         new_values, handled = process_data(data)         for value in new_values:             client_socket.send(str(value).encode() + "\n")         data = data[handled:] except serial.SerialException as e:     print("串口连接错误:", e) except socket.error as e:     print("网络连接错误:", e) finally:     # 关闭串口和套接字     ser.close()     server_socket.close()

**Comment by LandyZou** [comment]
请问可以在同一台电脑上运行这个脚本和serialtest tcp服务器吗？


----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Self&nbsp;Not&nbsp;Found ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 晚上6:47
收件人："wh201906/SerialTest" ***@***.***&gt;;
抄送："邹浪 ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [wh201906/SerialTest] 可以自定义数据协议吗？ (Issue #35)
-----------------------------------

 

 
大概是这么个样子，因为没设备测试所以你要自己试一下
 import serial import socket # 串口配置 SERIAL_PORT = "COM3"  # 替换为你的串口号 BAUD_RATE = 9600  # 波特率，根据实际情况修改 # TCP服务器配置 SERVER_IP = "0.0.0.0"  # 监听所有可用的网络接口 SERVER_PORT = 12345  # 替换为服务器的端口号 # 数据包格式 PACKET_HEAD = b"\xAA\xFF\xF1" PACKET_LEN = 8 # 处理数据 def process_data(data):     ptr = 0     handled = 0     values = []     while True:         ptr = data.find(PACKET_HEAD, handled)         if ptr == -1:             break         if len(data) - ptr < PACKET_LEN:             break         value = data[ptr + 4] + (data[ptr + 5] << 8)         values.append(value)         handled = ptr + PACKET_LEN     return values, handled # 创建串口对象 ser = serial.Serial(SERIAL_PORT, BAUD_RATE) # 创建TCP服务器套接字 server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) try:     # 绑定服务器地址和端口     server_socket.bind((SERVER_IP, SERVER_PORT))     print("服务器已启动，正在监听端口", SERVER_PORT)     # 开始监听连接     server_socket.listen(1)     # 等待客户端连接     client_socket, client_address = server_socket.accept()     print("已连接到客户端", client_address)     values = []     data = bytearray()     while True:         # 从串口读取数据         new_data = ser.read_all()         if new_data is not None:             data += new_data         new_values, handled = process_data(data)         for value in new_values:             client_socket.send(str(value).encode() + "\n")         data = data[handled:] except serial.SerialException as e:     print("串口连接错误:", e) except socket.error as e:     print("网络连接错误:", e) finally:     # 关闭串口和套接字     ser.close()     server_socket.close()

**Comment by LandyZou** [comment]
虚拟串口，两边都是通的，发送内容也是对的

<img width="1203" alt="微信图片_20230620095222" src="https://github.com/wh201906/SerialTest/assets/92777893/b1028c32-a7d6-4462-b889-f95c288bb5f6">


但是用你给的那个py脚本做TCP转发，程序运行到读串口的内容的时候，会把最后8位解码成对应的ASCII码，不知道为什么

<img width="498" alt="微信图片_202306200952222" src="https://github.com/wh201906/SerialTest/assets/92777893/5e71ae63-2a9b-4e6c-892a-29d582d4c2e7">


<img width="121" alt="微信图片_202306200952223" src="https://github.com/wh201906/SerialTest/assets/92777893/8277fcde-fd6a-4927-b9e4-bfd9878b377a">


TCP接收到的内容好像也不是很正确

<img width="1202" alt="微信图片_202306200952221" src="https://github.com/wh201906/SerialTest/assets/92777893/b8904d12-63cf-4f2a-8a2d-704d083c152b">

**Comment by wh201906** [comment]
@LandyZou 我测下来是可以正常工作的。你改波特率了吗？
![图片](https://github.com/wh201906/SerialTest/assets/62299611/268b399c-c8fd-4481-bf4b-79ebdab719b7)
