### ISSUE TITLE
macos qt6.4.2编译提示bluetooth模块找不到

### ISSUE THREAD

**Issue by zhjc2014** [wh201906/SerialTest#39]
### 编译错误提示
:-1: error: Unknown module(s) in QT: bluetooth 

### 系统信息
MacBook Pro
14英寸，2021年
芯片 Apple M1 Pro
内存 16GB
序列号 Y7YYNC6390
macOS Ventura 13.3.1 (a)

### qt信息
Qt Creator 9.0.2
Based on Qt 6.4.2 (Clang 13.0 (Apple), arm64)

Built on Feb 21 2023 02:24:53

From revision [78218cd601](https://code.qt.io/cgit/qt-creator/qt-creator.git/log/?id=78218cd601ed64407b43eb30f19eac944f65a826)

Copyright 2008-2022 The Qt Company Ltd. All rights reserved.

The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

The Qt logo as well as Qt®, Qt Quick®, Built with Qt®, Boot to Qt®, Qt Quick Compiler®, Qt Enterprise®, Qt Mobile® and Qt Embedded® are registered trademarks of The Qt Company Ltd.

**Comment by wh201906** [comment]
这个项目目前还没有适配Qt6，只支持Qt5
你可以参考macOS CI来编译，也可以直接在里面下载编译打包好的dmg文件
https://github.com/wh201906/SerialTest/actions/workflows/build-macos.yml
release里面也有编译打包好的dmg文件
