### ISSUE TITLE
图例显示功能建议

### ISSUE THREAD

**Issue by a276994712** [wh201906/SerialTest#43]
能否考虑设置增加，x，y轴的图例，可以手动设置x，y 分别代表什么，显示在坐标轴旁边

**Comment by wh201906** [comment]
在坐标轴附近加x, y轴图例会占用一部分绘图面积，在手机这种小尺寸的设备上会显得有效绘图面积很小。似乎不太必要？
你有什么具体的应用场景吗？现在已有的图例功能相当于你所说的y轴图例，并且支持多条曲线

**Comment by a276994712** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by a276994712** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
