### ISSUE TITLE
接收大小写问题

### ISSUE THREAD

**Issue by Ruby-Summer** [wh201906/SerialTest#56]
你好，我发送字符无论是大写还是小写接收到的都是小写，因为有时候需要区分大小写，是软件本身就是这样还是有哪里可以设置是我没发现的
![屏幕截图 2024-03-13 002431](https://github.com/wh201906/SerialTest/assets/46600094/8bf8b51b-e240-4ef1-a97d-ee7e77197202)

**Comment by wh201906** [comment]
可以截个完整的窗口图片吗？我看下其他设置

**Comment by Ruby-Summer** [comment]
我发现是16进制的问题 ，勾选16进制就会把发送的字母改为小写，其他什么设置都没更改
![屏幕截图 2024-03-13 105217](https://github.com/wh201906/SerialTest/assets/46600094/7c95b0ef-5185-4fc9-b3fd-277f36dfb3c5)

**Comment by wh201906** [comment]
因为16进制的数据不需要区分大小写啊，这种情况下AA和aa都代表相同的数据

**Comment by Ruby-Summer** [comment]
不好意思，是我这边的问题，代码有个历史遗留问题，有个判断是否正确接收到要的数据是根据大写 FF 判断的，昨天太累了发现这个问题就没多想，抱歉耽误你时间了，感谢你的回复

**Comment by wh201906** [comment]
没事儿
