### ISSUE TITLE
[建议] 接收数据框能实时显示最后一次接收的数据

### ISSUE THREAD

**Issue by akatong** [wh201906/SerialTest#57]
![image](https://github.com/wh201906/SerialTest/assets/20764318/eb3c51ac-7f79-414f-949b-2361c75cc3c9)
每次下发完指令，接收框的数据都不会实时拉到底显示，每次都要拖动下拉到后面，才知道指令回复了什么内容，这个不太方便。。最好是有一个开关，可以选择是否每次都显示最底部的数据。

**Comment by wh201906** [comment]
勾选“显示最新数据”即可

**Comment by akatong** [comment]
![image](https://github.com/wh201906/SerialTest/assets/20764318/49f7f63d-4256-4bee-9315-868dac4767b1)
确实有，因为分辨率原因，以为那里没有个勾选框，，，哈哈

**Comment by akatong** [comment]
![PixPin_2024-03-13_09-19-58](https://github.com/wh201906/SerialTest/assets/20764318/b0092181-d0f9-471a-ae57-96577cf15fb3)
但还是有个问题，每次都不会定位在最后一行数据，还是要下拉一定的距离。

**Comment by wh201906** [comment]
这个问题倒是确实存在，等我试着修一下

**Comment by wh201906** [comment]
已在 a6ee785ae135cd371db67fed7417e2b331899eba 当中修复  
你可以在这里下载CI编译好的版本  
https://github.com/wh201906/SerialTest/actions/runs/8572806409
