### ISSUE TITLE
[建议]  数据接收一栏，是否可以有个自动存储功能，可以实时存储数据并存放到设置的目录中

### ISSUE THREAD

**Issue by akatong** [wh201906/SerialTest#61]
![image](https://github.com/wh201906/SerialTest/assets/20764318/0f561cad-aae3-4630-a917-e86f4076e6d1)

数据接收这块，希望有个开关可以开启自动存储功能：
1. 每次连接上一个端口，按当前时间戳为文件名字自动生成一个txt文件，并实时存储数据。
2. 如果端口重新连接，会自动以当前时间戳为名字重新生成一个txt文件，并实时存储数据。

这对挂机自动收发数据，并记录长时间交互日志，很有帮助。
另外，想确认下当前 导出功能，能导出的的最大缓存是多少？有没有上限？

**Comment by wh201906** [comment]
整个重连这块都还没做，得等后期加功能了
数据接收这块你可以试一下文件收发功能，文件收发和数据是可以同时运行的，这样就相当于接收的同时保存到日志了，就是不算很方便
目前Qt5编译的版本在数据面板只能接收2GBytes的数据，超过会崩溃。这是Qt的窗口控件的限制，目前没办法解决。但如果你取消“实时刷新”选项和“显示最新数据”选项，只在文件收发面板接收数据，那可以导出到硬盘满为止，因为每接收到一小段数据就会写到硬盘上。

**Comment by akatong** [comment]
嗯，了解了，目前看无论是数据接收还是文件收发，是满足现有的需求的👍🙂
