### ISSUE TITLE
源码重新编译出错

### ISSUE THREAD

**Issue by LandyZou** [wh201906/SerialTest#62]
使用的是Qt5.15.2 MinGW 64-bit的环境，直接运行源码报错error: cannot find -lqcustomplotd2

**Comment by wh201906** [comment]
你需要下载QCustomPlot的源码，并将qcustomplot.cpp放到src文件夹下，再编译
下载链接可参考README当中的Linux编译步骤

**Comment by LandyZou** [comment]
![image](https://github.com/wh201906/SerialTest/assets/92777893/301bc93d-e7a8-4a32-8b38-6498452a91c7)
添加了qcustomplot.cpp之后，报错： error: multiple definition of `QCPVector2D::QCPVector2D()'.....

**Comment by wh201906** [comment]
只需要把qcustomplot.cpp放到src/文件夹下，不要修改.pro文件

**Comment by Lucas-CX** [comment]
在windows上编译，添加了qcustomplot.cpp，报的和楼主一样的错，请问楼主解决了么？ @LandyZou

**Comment by LandyZou** [comment]
@Lucas-CX 我之前下载源码没有添加qcustomplot.cpp，编译出错之后，自己鼓捣了一下，还是没有解决五问题，最后在项目发布者的提示下，添加了qcustomplot.cpp，编译仍然出错，就在想是不是因为之前自己瞎鼓捣修给了一些配置，然后重新解压源码，直接将qcustomplot.cpp添加到src/文件夹下，直接编译就成功编译了。我是使用Qt 5.15.2 MinGW进行编译的。

**Comment by wh201906** [comment]
@LandyZou 既然已经编译成功了，那我就先关闭这个issue了
@Lucas-CX 如果你遇到`multiple definition`的错误，请参考[此评论](https://github.com/wh201906/SerialTest/issues/62#issuecomment-1998926287)重新编译。后续有问题可以继续在这个issue下回复

**Comment by Lucas-CX** [comment]
@LandyZou @wh201906 已编译成功，十分感谢各位！！！
