### ISSUE TITLE
[建议] PC端增加记录窗口排版的功能

### ISSUE THREAD

**Issue by akatong** [wh201906/SerialTest#63]
目前有两个建议：
1. 当前每次打开软件，都是默认的排版格式，之前排好版的风格，需要重新再排一次...不太方便，希望程序能自动记录上一次排版风格。
2. 控制窗口，每次打开软件，都需要手动导入一次上一次存储的配置，这样也不太方便，如果能记录上一次导入的配置就好了。

![image](https://github.com/wh201906/SerialTest/assets/20764318/1cb08728-b7d7-44f9-97f7-b24a8a3d67cf)

**Comment by wh201906** [comment]
> 希望程序能自动记录上一次排版风格

这个我之后看看怎么做

> 这样也不太方便，如果能记录上一次导入的配置就好了

你可以试试把已有的配置文件直接拖动到控制窗口里面，这样会方便些

**Comment by akatong** [comment]
嗯，目前SerialTest更多的可能是小问题小优化的修补增加。

还发现一个不方便的地方：
打开一个串口后，如果想切换到另一个串口，直接点打开会提示：串口已打开的错误，不能直接切换到到另一个串口，必须要先点一次关闭，再点击一次打开，不太便捷。

如果能选中列表中一个端口后，直接点打开，就可以立即切换就好了。

**Comment by wh201906** [comment]
> 如果能选中列表中一个端口后，直接点打开，就可以立即切换就好了。

我感觉这样做相当于单击打开按钮之后会自动关闭当前连接，但我觉得这种设计不稳妥。

**Comment by wh201906** [comment]
你说的有几个小问题都在新版本(V0.3.5)当中修复了。你可以下载下来试一下
