### ISSUE TITLE
老哥有空添加个导出整个软件的配置的接口呗

### ISSUE THREAD

**Issue by h-zhaohe** [wh201906/SerialTest#8]
期望能够导出诸如UI布局，指令，绘图配置等所有配置的导出导入接口。

另外：
  老哥README添加个捐赠途径。

**Comment by wh201906** [comment]
目前指令面板的内容有单独的导入导出按钮，其它界面的内容可以通过复制preference.ini来迁移
这只是一个小软件，因此暂不考虑捐赠

**Comment by wh201906** [comment]
@h-zhaohe 现在Android端和PC端都支持以文件的形式来导入/导出所有配置
