### ISSUE TITLE
modbus通讯

### ISSUE THREAD

**Issue by NMX141324** [wh201906/SerialTest#84]
您好请问怎么进行modbus RTU通讯 ，另外软件有帮助手册吗请问？，谢谢

**Comment by wh201906** [comment]
> 您好请问怎么进行modbus RTU通讯

目前还没有modbus功能

> 另外软件有帮助手册吗请问？

之前做了一个简易版的教程，界面可能和目前的有些区别
https://github.com/wh201906/SerialTest/blob/master/doc/README/README_zh_CN.md#%E6%95%99%E7%A8%8B%E6%9C%AA%E5%AE%8C%E5%B7%A5

**Comment by NMX141324** [comment]
谢谢
